git:
  branch: master

wants:
  mongo: true

secrets:
  - GROUND_TRUTH_ID
  - GROUND_TRUTH_SECRET
  - SESSION_SECRET
  - GRAPHQL_AUTH
  - SUBMIT_SECRET

health:
  path: /status

env:
  GROUND_TRUTH_URL: https://login.hack.gt
  DEVPOST_URL: https://hackgt2020.devpost.com/
  PORT: 3000
  PRODUCTION: true
  MEET_URL: https://meet.hack.gt
